runtime:
  name: mixed-bus-win-mock
  shutdown_timeout_ms: 3000
  startup_timeout_ms: 30000
http:
  enabled: true
  bind: 127.0.0.1
  port: 18080
  cors_allow_credentials: false
  cors_allowed_origins:
  - http://localhost:3000
  - http://127.0.0.1:3000
providers:
- id: bread0
  command: ../anolis-provider-bread/build/dev-release/anolis-provider-bread
  args:
  - --config
  - ../anolis-projects/projects/mixed-bus-mock/config/provider-bread.bread0.yaml
  timeout_ms: 5000
  hello_timeout_ms: 2000
  ready_timeout_ms: 10000
  restart_policy:
    enabled: true
    max_attempts: 3
    backoff_ms:
    - 200
    - 500
    - 1000
    timeout_ms: 30000
- id: ezo0
  command: ../anolis-provider-ezo/build/dev-release/anolis-provider-ezo
  args:
  - --config
  - ../anolis-projects/projects/mixed-bus-mock/config/provider-ezo.ezo0.yaml
  timeout_ms: 5000
  hello_timeout_ms: 2000
  ready_timeout_ms: 10000
  restart_policy:
    enabled: true
    max_attempts: 3
    backoff_ms:
    - 200
    - 500
    - 1000
    timeout_ms: 30000
polling:
  interval_ms: 500
telemetry:
  enabled: false
logging:
  level: info
automation:
  enabled: false
