name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions: read-all

jobs:
  check:
    uses: anolishq/.github/.github/workflows/docs-check.yml@e993ae623cdaebfaef4e4a25ac806f269a6a2f86 # v2
